# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  test:
    docker:
      - image: denoland/deno:1.34.3
    steps:
      - checkout
      - run: |
          deno test src/**/*.spec.ts

workflows:
  opentimes:
    jobs:
      - test
